# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "features/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env: 
      ASPNETCORE_ENVIRONMENT: github

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test computation
      run: dotnet test --no-build --filter "UnitTest=Computation"
      working-directory: src
    - name: Test content import
      run: dotnet test --no-build --filter "UnitTest=ContentImport"
      working-directory: src
    - name: Test content generation
      run: dotnet test --no-build --filter "UnitTest=ContentGeneration"
      working-directory: src
    - name: Test XML serialization
      run: dotnet test --no-build --filter "UnitTest=XmlSerialization"
      working-directory: src
