# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "features/*" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      checks: write
      contents: read
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      ASPNETCORE_ENVIRONMENT: github
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test computation
        if: always()
        run: dotnet test --no-build --filter-trait-trait "UnitTest=Computation" --report-trx --report-trx-filename computation.trx --results-directory ../TestResults
      - name: Test consistency
        if: always()
        run: dotnet test --no-build --filter-trait "UnitTest=ConsistencyCheck" --report-trx --report-trx-filename consistency.trx --results-directory ../TestResults
      - name: Test content import
        if: always()
        run: dotnet test --no-build --filter-trait "UnitTest=ContentImport" --report-trx --report-trx-filename content-import.trx --results-directory ../TestResults
      - name: Test content generation
        if: always()
        run: dotnet test --no-build --filter-trait "UnitTest=ContentGeneration" --report-trx --report-trx-filename content-generation.trx --results-directory ../TestResults
      - name: Test XML serialization
        if: always()
        run: dotnet test --no-build --filter-trait "UnitTest=XmlSerialization" --report-trx --report-trx-filename xml-serialization.trx --results-directory ../TestResults
      - name: Test Security
        if: always()
        run: dotnet test --no-build --filter-trait "UnitTest=Security" --report-trx --report-trx-filename security.trx --results-directory ../TestResults

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test results
          path: 'TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: true